spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

# to do clear it
hh:
  search:
    keyword: Java
    search-field: name
    area: 1
    min-salary: 0
    currency: RUR
    only-with-salary: false
    per-page: 50

server:
  port: 8080
